/**
 * <Div>ine - The Movie Database
 * Structured movie repository with comic ratings, funny captions, trailers & trivia
 */

const moviesDB = [
    // ==========================================
    // ACTION
    // ==========================================
    {
        id: "john-wick-4",
        title: "John Wick 4",
        genre: "Action",
        year: 2023,
        rating: 7.7,
        runtime: "169 min",
        director: "Chad Stahelski",
        img: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
        caption: "Local dog lover kills 400 people on stairs.",
        synopsis: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.",
        verdict: "Do NOT touch anyone's dog. Ever.",
        trailerId: "qEVUtrk8_B4",
        tags: ["explosions", "guns", "adrenaline", "suits"]
    },
    {
        id: "bullet-train",
        title: "Bullet Train",
        genre: "Action",
        year: 2022,
        rating: 7.3,
        runtime: "126 min",
        director: "David Leitch",
        img: "https://image.tmdb.org/t/p/w500/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
        caption: "Thomas the Tank Engine for certified psychopaths.",
        synopsis: "Five assassins aboard a swiftly-moving bullet train find out that their missions have something in common.",
        verdict: "Brad Pitt wearing a bucket hat dodging swords.",
        trailerId: "0IOsk2Vun8Q",
        tags: ["train", "assassins", "fun", "chaos"]
    },
    {
        id: "dhoom",
        title: "Dhoom",
        genre: "Action",
        year: 2004,
        rating: 6.6,
        runtime: "129 min",
        director: "Sanjay Gadhvi",
        img: "dhoom.jpeg",
        caption: "Physics has left the chat on a Hayabusa.",
        synopsis: "A mysterious gang of bikers starts robbing banks across Mumbai, leading an eccentric cop and a local mechanic on a high-speed chase.",
        verdict: "Every 2000s kid suddenly wanted a superbike.",
        trailerId: "drQ9t5bFmJc",
        tags: ["bikes", "bollywood", "nitro", "heist"]
    },
    {
        id: "jawan",
        title: "Jawan",
        genre: "Action",
        year: 2023,
        rating: 7.0,
        runtime: "169 min",
        director: "Atlee",
        img: "jawan.jpg",
        caption: "Too many bandages, infinite unstoppable swag.",
        synopsis: "A high-voltage action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society.",
        verdict: "Shah Rukh Khan entering like a meteor strike.",
        trailerId: "COv52Qyctws",
        tags: ["srk", "metro", "rebellion", "masala"]
    }
];
    {
        id: "mad-max-fury-road",
        title: "Mad Max: Fury Road",
        genre: "Action",
        year: 2015,
        rating: 8.1,
        runtime: "120 min",
        director: "George Miller",
        img: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
        caption: "A 2-hour U-turn in the desert with a flame-throwing guitar.",
        synopsis: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
        verdict: "Witness me shiny and chrome!",
        trailerId: "hEJnMQG938g",
        tags: ["desert", "cars", "flames", "insane"]
    },
    {
        id: "kgf-chapter-2",
        title: "K.G.F: Chapter 2",
        genre: "Action",
        year: 2022,
        rating: 8.2,
        runtime: "168 min",
        director: "Prashanth Neel",
        img: "https://image.tmdb.org/t/p/w500/6A7uqgC2N1nU3nvd0xVn7fQ12Jq.jpg",
        caption: "Violence violence violence. He avoids, but violence likes him.",
        synopsis: "In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes. While his allies look up to him, the government sees him as a threat to law and order.",
        verdict: "High-octane smoking slow-motion masculinity.",
        trailerId: "JKa05nyUmuQ",
        tags: ["gold", "monologue", "mass", "power"]
    },
    {
        id: "top-gun-maverick",
        title: "Top Gun: Maverick",
        genre: "Action",
        year: 2022,
        rating: 8.3,
        runtime: "130 min",
        director: "Joseph Kosinski",
        img: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
        caption: "Tom Cruise refusing to use CGI or age like a normal human.",
        synopsis: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on an impossible mission.",
        verdict: "Danger zone never sounded so exhilarating.",
        trailerId: "giXco2jaZ_4",
        tags: ["jets", "flying", "adrenaline", "danger"]
    },
    // ==========================================
    // COMEDY
    // ==========================================
    {
        id: "the-hangover",
        title: "The Hangover",
        genre: "Comedy",
        year: 2009,
        rating: 7.7,
        runtime: "100 min",
        director: "Todd Phillips",
        img: "hangover.jpg",
        caption: "Why you should never go to Vegas without an adult supervisor.",
        synopsis: "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They must make their way around the city in order to find their friend before his wedding.",
        verdict: "There is a tiger in the bathroom and a baby in the closet.",
        trailerId: "tcdUhdOlz9M",
        tags: ["vegas", "hangover", "wild", "chaos"]
    },
    {
        id: "the-mask",
        title: "The Mask",
        genre: "Comedy",
        year: 1994,
        rating: 6.9,
        runtime: "101 min",
        director: "Chuck Russell",
        img: "mask.jpeg",
        caption: "S-s-s-smokin'! Peak Jim Carrey energy unleashed.",
        synopsis: "Bank clerk Stanley Ipkiss is transformed into a manic superhero when he wears a mysterious Norse god mask.",
        verdict: "Yellow zoot suit and physics-breaking jaw drops.",
        trailerId: "LZl69yk5lEY",
        tags: ["jimcarrey", "green", "cartoon", "classic"]
    },
    {
        id: "dhamaal",
        title: "Dhamaal",
        genre: "Comedy",
        year: 2007,
        rating: 7.4,
        runtime: "137 min",
        director: "Indra Kumar",
        img: "dhamaal.jpg",
        caption: "Looking for a big 'W' under a palm tree in Goa.",
        synopsis: "Four lazy slackers and a police inspector embark on a cross-country treasure hunt to unearth 10 crore rupees hidden in Goa.",
        verdict: "Aditya, Manav, and the red champagne car that never dies.",
        trailerId: "6Q9qX9i5g5M",
        tags: ["goa", "treasure", "manav", "slapstick"]
    },
    {
        id: "hera-pheri",
        title: "Hera Pheri",
        genre: "Comedy",
        year: 2000,
        rating: 8.2,
        runtime: "156 min",
        director: "Priyadarshan",
        img: "hera pheri.jpeg",
        caption: "21 days to double your money. Totally legit scheme.",
        synopsis: "Two tenants and a landlord in desperate need of money chance upon a ransom call meant for someone else and concoct a plan.",
        verdict: "Babu Bhaiya is the undisputed king of Indian memes.",
        trailerId: "3K1Hh5Gz1kU",
        tags: ["baburao", "memes", "bollywood", "legendary"]
    },
    {
        id: "3-idiots",
        title: "3 Idiots",
        genre: "Comedy",
        year: 2009,
        rating: 8.4,
        runtime: "170 min",
        director: "Rajkumar Hirani",
        img: "https://image.tmdb.org/t/p/w500/7492A7wSZyW6eUjW1n1C6M9rJ4S.jpg",
        caption: "All Izz Well (except the engineering semester exams).",
        synopsis: "Two friends search for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.",
        verdict: "Pursue excellence and success will chase you with pants down.",
        trailerId: "K0eDlFX9GMc",
        tags: ["engineering", "college", "friendship", "inspirational"]
    },
    {
        id: "superbad",
        title: "Superbad",
        genre: "Comedy",
        year: 2007,
        rating: 7.6,
        runtime: "113 min",
        director: "Greg Mottola",
        img: "https://image.tmdb.org/t/p/w500/ek8e8txUyUvd2BNqj6LKi0Il1dQ.jpg",
        caption: "McLovin: One name, 25-year-old Hawaiian organ donor.",
        synopsis: "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.",
        verdict: "Fogell will forever be known as McLovin.",
        trailerId: "4eaZ_48ZYog",
        tags: ["mclovin", "highschool", "party", "nostalgia"]
    },
    // ==========================================
    // ROMANCE
    // ==========================================
    {
        id: "titanic",
        title: "Titanic",
        genre: "Romance",
        year: 1997,
        rating: 7.9,
        runtime: "195 min",
        director: "James Cameron",
        img: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
        caption: "Spoiler: The boat sinks, and that door definitely had room for two.",
        synopsis: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        verdict: "Rose could have slid over 4 inches to save Jack.",
        trailerId: "kVrqfYjkTdQ",
        tags: ["door", "iceberg", "drawing", "tears"]
    },
    {
        id: "the-notebook",
        title: "The Notebook",
        genre: "Romance",
        year: 2004,
        rating: 7.8,
        runtime: "123 min",
        director: "Nick Cassavetes",
        img: "https://image.tmdb.org/t/p/w500/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg",
        caption: "Crying guaranteed or your money back with interest.",
        synopsis: "An elderly man reads to a woman with dementia the story of two young lovers who were separated by their social differences.",
        verdict: "If you're a bird, I'm a bird. *sniffle*",
        trailerId: "FC6biTjEyZw",
        tags: ["rain", "letters", "lake", "swans"]
    },
    {
        id: "om-shanti-om",
        title: "Om Shanti Om",
        genre: "Romance",
        year: 2007,
        rating: 6.8,
        runtime: "162 min",
        director: "Farah Khan",
        img: "om.jpg",
        caption: "Reincarnation: The ultimate comeback for Bollywood stardom.",
        synopsis: "In the 1970s, Om, an aspiring actor, is murdered, but is reincarnated in the present day to discover the mystery of his death and find his true love.",
        verdict: "Picture abhi baaki hai mere dost!",
        trailerId: "NBw5YScs8iQ",
        tags: ["srk", "deepika", "reincarnation", "retro"]
    },
    {
        id: "la-la-land",
        title: "La La Land",
        genre: "Romance",
        year: 2016,
        rating: 8.0,
        runtime: "128 min",
        director: "Damien Chazelle",
        img: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkVJb0Rf0.jpg",
        caption: "Two pretty people tap-dance their way into bittersweet heartbreak.",
        synopsis: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
        verdict: "That final look at the jazz bar destroyed an entire generation.",
        trailerId: "0pdqf4P9MB8",
        tags: ["jazz", "tapdance", "sunset", "dreams"]
    },
    {
        id: "jab-we-met",
        title: "Jab We Met",
        genre: "Romance",
        year: 2007,
        rating: 7.9,
        runtime: "138 min",
        director: "Imtiaz Ali",
        img: "https://image.tmdb.org/t/p/w500/gH04kL8P36B73n3X3p3x3i7k8n0.jpg",
        caption: "Main apni favourite hoon: The ultimate self-love anthem.",
        synopsis: "A depressed wealthy businessman finds his life changing after he meets a bubbly and talkative young woman on a train.",
        verdict: "Geet taught the world how to never shut up and still be lovable.",
        trailerId: "Hf_7k6Rsm4E",
        tags: ["train", "geet", "bhatinda", "wholesome"]
    },
    // ==========================================
    // HORROR
    // ==========================================
    {
        id: "it",
        title: "It",
        genre: "Horror",
        year: 2017,
        rating: 7.3,
        runtime: "135 min",
        director: "Andy Muschietti",
        img: "https://image.tmdb.org/t/p/w500/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg",
        caption: "Never talk to demonic dancing clowns lurking in storm drains.",
        synopsis: "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry.",
        verdict: "You'll float too... into lifelong coulrophobia.",
        trailerId: "FnCdOQsX5kc",
        tags: ["clown", "balloon", "sewer", "fear"]
    },
    {
        id: "the-conjuring",
        title: "The Conjuring",
        genre: "Horror",
        year: 2013,
        rating: 7.5,
        runtime: "112 min",
        director: "James Wan",
        img: "conjuring.jpeg",
        caption: "Clap clap in the dark wardrobe. Instant cardiac arrest.",
        synopsis: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
        verdict: "Hide and Clap will never be played in this house again.",
        trailerId: "k10ETZ41q5o",
        tags: ["ghost", "doll", "basement", "possession"]
    },
    {
        id: "stree",
        title: "Stree",
        genre: "Horror",
        year: 2018,
        rating: 7.5,
        runtime: "128 min",
        director: "Amar Kaushik",
        img: "https://upload.wikimedia.org/wikipedia/en/4/4f/Stree_-_2018_Movie_Poster.jpg",
        caption: "O Stree kal aana! (Please don't show up tonight, or tomorrow).",
        synopsis: "In the small town of Chanderi, the menfolk live in fear of an evil spirit named Stree who abducts men in the night.",
        verdict: "Respect women, or else she will literally take your clothes.",
        trailerId: "gze8xBdW3T4",
        tags: ["chanderi", "comedy-horror", "saree", "folklore"]
    },
    {
        id: "tumbbad",
        title: "Tumbbad",
        genre: "Horror",
        year: 2018,
        rating: 8.2,
        runtime: "104 min",
        director: "Rahi Anil Barve",
        img: "https://upload.wikimedia.org/wikipedia/en/4/41/Tumbbad_poster.jpg",
        caption: "Greed has no limits, and Hastar never gets enough flour.",
        synopsis: "A mythological story about a goddess who created the entire universe and the forbidden first child, Hastar, who hoards endless gold coins in a dripping mansion.",
        verdict: "Masterclass Indian horror atmosphere with 10/10 visuals.",
        trailerId: "sN75MPHgvX8",
        tags: ["hastar", "greed", "rain", "mythology"]
    },
    {
        id: "get-out",
        title: "Get Out",
        genre: "Horror",
        year: 2017,
        rating: 7.8,
        runtime: "104 min",
        director: "Jordan Peele",
        img: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
        caption: "Tea cups, silver spoons, and the most awkward family dinner in history.",
        synopsis: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
        verdict: "The Sunken Place will keep you awake at night.",
        trailerId: "DzfpyUB60YY",
        tags: ["teacup", "sunkenplace", "suspense", "mindgames"]
    },
