/**
 * <Div>ine - The Movie Database
 * Structured movie repository with comic ratings, funny captions, trailers & trivia
 */

const moviesDB = [
    // ==========================================
    // ACTION
    // ==========================================
    {
        id: "john-wick-4",
        title: "John Wick 4",
        genre: "Action",
        year: 2023,
        rating: 7.7,
        runtime: "169 min",
        director: "Chad Stahelski",
        img: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
        caption: "Local dog lover kills 400 people on stairs.",
        synopsis: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.",
        verdict: "Do NOT touch anyone's dog. Ever.",
        trailerId: "qEVUtrk8_B4",
        tags: ["explosions", "guns", "adrenaline", "suits"]
    },
    {
        id: "bullet-train",
        title: "Bullet Train",
        genre: "Action",
        year: 2022,
        rating: 7.3,
        runtime: "126 min",
        director: "David Leitch",
        img: "https://image.tmdb.org/t/p/w500/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
        caption: "Thomas the Tank Engine for certified psychopaths.",
        synopsis: "Five assassins aboard a swiftly-moving bullet train find out that their missions have something in common.",
        verdict: "Brad Pitt wearing a bucket hat dodging swords.",
        trailerId: "0IOsk2Vun8Q",
        tags: ["train", "assassins", "fun", "chaos"]
    },
    {
        id: "dhoom",
        title: "Dhoom",
        genre: "Action",
        year: 2004,
        rating: 6.6,
        runtime: "129 min",
        director: "Sanjay Gadhvi",
        img: "dhoom.jpeg",
        caption: "Physics has left the chat on a Hayabusa.",
        synopsis: "A mysterious gang of bikers starts robbing banks across Mumbai, leading an eccentric cop and a local mechanic on a high-speed chase.",
        verdict: "Every 2000s kid suddenly wanted a superbike.",
        trailerId: "drQ9t5bFmJc",
        tags: ["bikes", "bollywood", "nitro", "heist"]
    },
    {
        id: "jawan",
        title: "Jawan",
        genre: "Action",
        year: 2023,
        rating: 7.0,
        runtime: "169 min",
        director: "Atlee",
        img: "jawan.jpg",
        caption: "Too many bandages, infinite unstoppable swag.",
        synopsis: "A high-voltage action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society.",
        verdict: "Shah Rukh Khan entering like a meteor strike.",
        trailerId: "COv52Qyctws",
        tags: ["srk", "metro", "rebellion", "masala"]
    }
];
    {
        id: "mad-max-fury-road",
        title: "Mad Max: Fury Road",
        genre: "Action",
        year: 2015,
        rating: 8.1,
        runtime: "120 min",
        director: "George Miller",
        img: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
        caption: "A 2-hour U-turn in the desert with a flame-throwing guitar.",
        synopsis: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
        verdict: "Witness me shiny and chrome!",
        trailerId: "hEJnMQG938g",
        tags: ["desert", "cars", "flames", "insane"]
    },
    {
        id: "kgf-chapter-2",
        title: "K.G.F: Chapter 2",
        genre: "Action",
        year: 2022,
        rating: 8.2,
        runtime: "168 min",
        director: "Prashanth Neel",
        img: "https://image.tmdb.org/t/p/w500/6A7uqgC2N1nU3nvd0xVn7fQ12Jq.jpg",
        caption: "Violence violence violence. He avoids, but violence likes him.",
        synopsis: "In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes. While his allies look up to him, the government sees him as a threat to law and order.",
        verdict: "High-octane smoking slow-motion masculinity.",
        trailerId: "JKa05nyUmuQ",
        tags: ["gold", "monologue", "mass", "power"]
    },
    {
        id: "top-gun-maverick",
        title: "Top Gun: Maverick",
        genre: "Action",
        year: 2022,
        rating: 8.3,
        runtime: "130 min",
        director: "Joseph Kosinski",
        img: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
        caption: "Tom Cruise refusing to use CGI or age like a normal human.",
        synopsis: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on an impossible mission.",
        verdict: "Danger zone never sounded so exhilarating.",
        trailerId: "giXco2jaZ_4",
        tags: ["jets", "flying", "adrenaline", "danger"]
    },
    // ==========================================
    // COMEDY
    // ==========================================
    {
        id: "the-hangover",
        title: "The Hangover",
        genre: "Comedy",
        year: 2009,
        rating: 7.7,
        runtime: "100 min",
        director: "Todd Phillips",
        img: "hangover.jpg",
        caption: "Why you should never go to Vegas without an adult supervisor.",
        synopsis: "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They must make their way around the city in order to find their friend before his wedding.",
        verdict: "There is a tiger in the bathroom and a baby in the closet.",
        trailerId: "tcdUhdOlz9M",
        tags: ["vegas", "hangover", "wild", "chaos"]
    },
    {
        id: "the-mask",
        title: "The Mask",
        genre: "Comedy",
        year: 1994,
        rating: 6.9,
        runtime: "101 min",
        director: "Chuck Russell",
        img: "mask.jpeg",
        caption: "S-s-s-smokin'! Peak Jim Carrey energy unleashed.",
        synopsis: "Bank clerk Stanley Ipkiss is transformed into a manic superhero when he wears a mysterious Norse god mask.",
        verdict: "Yellow zoot suit and physics-breaking jaw drops.",
        trailerId: "LZl69yk5lEY",
        tags: ["jimcarrey", "green", "cartoon", "classic"]
    },
    {
        id: "dhamaal",
        title: "Dhamaal",
        genre: "Comedy",
        year: 2007,
        rating: 7.4,
        runtime: "137 min",
        director: "Indra Kumar",
        img: "dhamaal.jpg",
        caption: "Looking for a big 'W' under a palm tree in Goa.",
        synopsis: "Four lazy slackers and a police inspector embark on a cross-country treasure hunt to unearth 10 crore rupees hidden in Goa.",
        verdict: "Aditya, Manav, and the red champagne car that never dies.",
        trailerId: "6Q9qX9i5g5M",
        tags: ["goa", "treasure", "manav", "slapstick"]
    },
    {
        id: "hera-pheri",
        title: "Hera Pheri",
        genre: "Comedy",
        year: 2000,
        rating: 8.2,
        runtime: "156 min",
        director: "Priyadarshan",
        img: "hera pheri.jpeg",
        caption: "21 days to double your money. Totally legit scheme.",
        synopsis: "Two tenants and a landlord in desperate need of money chance upon a ransom call meant for someone else and concoct a plan.",
        verdict: "Babu Bhaiya is the undisputed king of Indian memes.",
        trailerId: "3K1Hh5Gz1kU",
        tags: ["baburao", "memes", "bollywood", "legendary"]
    },
    {
        id: "3-idiots",
        title: "3 Idiots",
        genre: "Comedy",
        year: 2009,
        rating: 8.4,
        runtime: "170 min",
        director: "Rajkumar Hirani",
        img: "https://image.tmdb.org/t/p/w500/7492A7wSZyW6eUjW1n1C6M9rJ4S.jpg",
        caption: "All Izz Well (except the engineering semester exams).",
        synopsis: "Two friends search for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.",
        verdict: "Pursue excellence and success will chase you with pants down.",
        trailerId: "K0eDlFX9GMc",
        tags: ["engineering", "college", "friendship", "inspirational"]
    },
    {
        id: "superbad",
        title: "Superbad",
        genre: "Comedy",
        year: 2007,
        rating: 7.6,
        runtime: "113 min",
        director: "Greg Mottola",
        img: "https://image.tmdb.org/t/p/w500/ek8e8txUyUvd2BNqj6LKi0Il1dQ.jpg",
        caption: "McLovin: One name, 25-year-old Hawaiian organ donor.",
        synopsis: "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.",
        verdict: "Fogell will forever be known as McLovin.",
        trailerId: "4eaZ_48ZYog",
        tags: ["mclovin", "highschool", "party", "nostalgia"]
    },
